services:
  - type: web
    name: hustle-webhook
    runtime: python
    buildCommand: ""
    startCommand: uvicorn ai_hustle_automator:app --host 0.0.0.0 --port 8000
    envVars:
      - key: STRIPE_SECRET_KEY
        value: your_stripe_secret_key_here
      - key: STRIPE_WEBHOOK_SECRET
        value: your_webhook_secret_here
      - key: OPENAI_API_KEY
        value: your_openai_key_here
      - key: TWITTER_BEARER_TOKEN
        value: your_twitter_token_here
      - key: SMTP_USERNAME
        value: your.email@gmail.com
      - key: SMTP_PASSWORD
        value: your_app_password_here
